import type { CategoryDefinition } from './types';

export const WORLD_PACK_ID = 'world';

export const WORLD_CATEGORY_DEFINITIONS: CategoryDefinition[] = [
  {
    id: 'population',
    label: 'Population',
    shortLabel: 'Population',
    family: 'demographics',
    unitLabel: 'people',
    formatter: 'compact-number',
    enabled: true,
    minRelativeDelta: 0.04,
    closeCallDelta: 0.08,
  },
  {
    id: 'land_area',
    label: 'Land area',
    shortLabel: 'Land area',
    family: 'geography',
    unitLabel: 'sq km',
    formatter: 'sq-km',
    enabled: true,
    minRelativeDelta: 0.05,
    closeCallDelta: 0.1,
  },
  {
    id: 'gdp',
    label: 'GDP',
    shortLabel: 'GDP',
    family: 'economy',
    unitLabel: 'USD',
    formatter: 'compact-currency',
    enabled: true,
    minRelativeDelta: 0.08,
    closeCallDelta: 0.14,
  },
  {
    id: 'gdp_per_capita',
    label: 'GDP per capita',
    shortLabel: 'GDP per capita',
    family: 'economy',
    unitLabel: 'USD',
    formatter: 'currency-per-capita',
    enabled: true,
    minRelativeDelta: 0.06,
    closeCallDelta: 0.12,
  },
  {
    id: 'life_expectancy',
    label: 'Life expectancy',
    shortLabel: 'Life expectancy',
    family: 'health',
    unitLabel: 'years',
    formatter: 'decimal-1',
    enabled: true,
    minRelativeDelta: 0.02,
    closeCallDelta: 0.05,
  },
  {
    id: 'urban_population_pct',
    label: 'Urban population',
    shortLabel: 'Urban population',
    family: 'demographics',
    unitLabel: '%',
    formatter: 'percent-1',
    enabled: true,
    minRelativeDelta: 0.04,
    closeCallDelta: 0.08,
  },
  {
    id: 'internet_users_pct',
    label: 'Internet users',
    shortLabel: 'Internet users',
    family: 'technology',
    unitLabel: '%',
    formatter: 'percent-1',
    enabled: true,
    minRelativeDelta: 0.03,
    closeCallDelta: 0.06,
  },
  {
    id: 'forest_area_pct',
    label: 'Forest area',
    shortLabel: 'Forest area',
    family: 'environment',
    unitLabel: '%',
    formatter: 'percent-1',
    enabled: true,
    minRelativeDelta: 0.05,
    closeCallDelta: 0.1,
  },
  {
    id: 'co2_per_capita',
    label: 'CO2 emissions per capita',
    shortLabel: 'CO2 per capita',
    family: 'environment',
    unitLabel: 'metric tons',
    formatter: 'decimal-1',
    enabled: true,
    minRelativeDelta: 0.08,
    closeCallDelta: 0.14,
  },
  {
    id: 'fertility_rate',
    label: 'Fertility rate',
    shortLabel: 'Fertility rate',
    family: 'health',
    unitLabel: 'births / woman',
    formatter: 'decimal-1',
    enabled: true,
    minRelativeDelta: 0.06,
    closeCallDelta: 0.1,
  },
  {
    id: 'renewable_electricity_pct',
    label: 'Renewable electricity output',
    shortLabel: 'Renewable electricity',
    family: 'environment',
    unitLabel: '%',
    formatter: 'percent-1',
    enabled: true,
    minRelativeDelta: 0.06,
    closeCallDelta: 0.12,
  },
  {
    id: 'exports_total',
    label: 'Exports of goods and services',
    shortLabel: 'Exports',
    family: 'economy',
    unitLabel: 'USD',
    formatter: 'compact-currency',
    enabled: true,
    minRelativeDelta: 0.08,
    closeCallDelta: 0.14,
  },
];
